### ISSUE TITLE
Help me! Cannot pull the master branch

### ISSUE THREAD

**Issue by RobinGuillard** [lkorczowski/Tinnitus-n-Sleep#11]
I got this error:
ssh: Could not resolve hostname github.com: Name or service not known fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

I have not changed any ssh parameter... How did it unplug/disconnect and what should I do to fix it?

**Comment by RobinGuillard** [comment]
For the time being I will continue on my feat_imp_check branch ...

**Comment by lkorczowski** [comment]
Did you get this error when pushing ?

please give me the detailed error for this commands:
```
git checkout master
git pull
```

```
git checkout feat_imp_check
git pull
```

```
git checkout feat_imp_check
git add some_file
git commit -m "some commit"
git push
```

```
git checkout feat_imp_check
git merge master -m "get CI features"
```

**Comment by RobinGuillard** [comment]
I got this error while pulling from master.

Very weird: I retried just now to generate the error, and now it seems to work just fine O_o

**Comment by RobinGuillard** [comment]
It seems the problem solved itself, which it definitly never does normally, so I'll keep you updated if there is any more trouble

**Comment by lkorczowski** [comment]
ok reopen this issue if needed
