### ISSUE TITLE
Inhomogénéité de grandeurs

### ISSUE THREAD

**Issue by RobinGuillard** [lkorczowski/Tinnitus-n-Sleep#13]
Les fonctions de utils se servent de duration et interval en nb d'échantillons alors que par ailleurs dans data duration et interval sont à exprimer en secondes. Du coup pour utiliser les 2 fonctions dans le même code on doit faire des conversions. C'est pas pratique!
Pa sévident de savoir ce qu'est le mieux entre temps et nb d'échantillons. Je préfère nb d'échantillon car pour le temps on pourrait arriver à faire des arrondis pour le nb d'échantillons.

**Comment by lkorczowski** [comment]
Proposed solution:
- [ ] removed `mne.Epochs` use in `RawToEpochs_sliding`, use instead `utils.epoch`
- [ ] correct `test_data()` accordingly
