### ISSUE TITLE
The notorious "check_if_fitted" command

### ISSUE THREAD

**Issue by RobinGuillard** [lkorczowski/Tinnitus-n-Sleep#20]
Hi louis!
Up until now, I had the situation: check_if_fitted is not running with spyder BUT it's working with pytest when I launch it from a terminal.
Since this morning, as I opened a new terminal for pytest, now it's not working on either of them and I get the same error:
TypeError: check_is_fitted() missing 1 required positional argument: 'attributes'

I strongly suggest you find another function or you add an argument attributes.

**Comment by lkorczowski** [comment]
closing for now because with removed the function altogether
