### ISSUE TITLE
Detect bruxism events with noise

### ISSUE THREAD

**Issue by RobinGuillard** [lkorczowski/Tinnitus-n-Sleep#21]
By re-reading research papers, I have identified that most of them cite the "number of episodes with noise". By noise they mean tooth grinding. In our case, we don't have sound recordings of our nights so we cannot totally identify teeth grinding (too bad) but we have an audio volume channel (in dB). Perhaps we can try to estimate which episodes generate sound on the micro and make a basic estimation of this metric!

**Comment by lkorczowski** [comment]
sound volume is not well suited for this task. It requires a better microphone to differentiate sounds.

Closing
