### ISSUE TITLE
Detect awake moments

### ISSUE THREAD

**Issue by RobinGuillard** [lkorczowski/Tinnitus-n-Sleep#24]
In many night patients tend to wake up, from a couple of minuts to 1 hour or more. We need to detect that as while awaken lots of events happen on the jaw channels while they are awake and they should not be counted as bruxism episodes.
We should definitely work on this as we will need it when we will go on on the middle ear contraction analysis.
They are different possibilities to accomplish this. The more obvious one is to use the hypnogram of the patient (we will have it in the future), the second best option is to use the "activity" channel of the recording and identify awakenings and movements. Then we can also identify moments where all EEG channels are artefacted + have more beta activity.

**Comment by RobinGuillard** [comment]
I have taken the time to inspect the data and I've made the observation that we cannot identify awakenings periods through the activity channel: I've seen that the great majority of jaw events are occurring in the same time as an activity burst, but also that there are long moments where patients can be awaken (and blinking) and there is nothing to be seen in the activity channel.
I suggest to wait the hypnograms, or to rely more on the EEG rhythm acceleration.

**Comment by lkorczowski** [comment]
awake events will be labeled manually

closing
