### ISSUE TITLE
raw.filter poor convergence

### ISSUE THREAD

**Issue by lkorczowski** [lkorczowski/Tinnitus-n-Sleep#40]
As the famous #38 shown, doing 
```
    raw = raw.filter(20., 99., n_jobs=4,
                     fir_design='firwin', filter_length='auto', phase='zero-double',
                     picks=picks_chan)
```
made our artefact rejection algorithm `is_good()` reject an entire chunk of data (e.g. 2 sec) while the artefact was only 1 sample. See figure below:
![image](https://user-images.githubusercontent.com/15196605/80025264-a2f92880-84e0-11ea-98d9-c2aab204af2e.png)

It is hard to see how bad is it in this figure, so here is the data at scale : 
![image](https://user-images.githubusercontent.com/15196605/80025392-dcca2f00-84e0-11ea-91af-9485c977bdc4.png)

Yep. That's bad.

We need to design a better filter.

**Comment by RobinGuillard** [comment]
Well let's put it in the good context as well: the data I designed was exagerately abnormal, I swiched from values of order 1e-7 to 100. It means 9 order of magnitude different. In this context, it appears to me that it's not really surprising the filter struggles to converge quickly...

**Comment by RobinGuillard** [comment]
As this case of 9 order of magnitude doesn't happen in practice (I feel quite safe to say it) I would be indulgent on it...

**Comment by lkorczowski** [comment]
You are right.

We will reopen this issue if with see a bad convergence on real data
