### ISSUE TITLE
Rejecting channels instead of rejecting epochs and possibly recordings

### ISSUE THREAD

**Issue by RobinGuillard** [lkorczowski/Tinnitus-n-Sleep#42]
Currently, the method we implemented has a strong drawback. Imagine we have a recording where a channel is disconnected and bad 100% of the time, and another channel is good 100% time. In this case, our algos currently decide that none of the epochs of this recording should be kept. It's a poor idea: we should be able to diagnose a channel as "mainly bad" and suppress it and analyse the signal on only the remaining good channels.
In fact, I suggest that we do something like: when one channel is bad over more than 50% of the time, if the other channel is good more than 50% of the time then we should delete the bad channel and make all the classification on the remaining good channel.

Please tell me what do you suggest in this matter.

**Comment by lkorczowski** [comment]
So we decided to add a .csv for bad channels after manual addressing each problematic recording
