### ISSUE TITLE
FYI Case insentive mac OS made git hell on earth

### ISSUE THREAD

**Issue by lkorczowski** [lkorczowski/Tinnitus-n-Sleep#47]
FYI

I'm working on Mac OS. To make life "easier" dev of Mac OS thought it would be better to have file system be case insensitive. They thought wrong.

At one point, we had two notebooks folder in the git system because of that
"notebooks/" and "Notebooks/"

I cleaned that but we should be careful to keep all folder in lowercap

**Comment by RobinGuillard** [comment]
Perfect, thank you!

"Bien vu"!

**Comment by lkorczowski** [comment]
solved using:
```
git mv OldFolder tmp
git mv tmp oldfolder
```

`Notebooks` renamed to `notebooks`
`resources`renamed to `data`

please get the modification in your banch @RobinGuillard 
by doing:
```
git checkout yourbranch
git merge feat-ear_report
```

**Comment by lkorczowski** [comment]
OK, so basically, I couldn't make it work on my site anyway because the only way to fix that is being on the case sensitive machine (source: https://www.drupaleasy.com/blogs/ultimike/2013/03/lesson-learned-i-cant-get-my-git-repo-clean).

So basically, I'm lucky to just have lost the work of this morning and if it works on you side, I just need to figure out how to come back to normal (maybe a clean git clone will make it works) because I'm stuck with the following error when I want to checkout:
```
(tinnsleep-env) MBP-de-Louis:notebooks louis$ git checkout master
error: The following untracked working tree files would be overwritten by checkout:
        Notebooks/Bruxism_comparison_adaptive.ipynb
        Notebooks/Bruxism_detection.ipynb
```

sadness

**Comment by lkorczowski** [comment]
We consider this issue solve. Robin made the modification on his case-sensitive machine and I git clone a clean repo. It worked.
