### ISSUE TITLE
Add ratio of power in the reporting for middle ear events

### ISSUE THREAD

**Issue by RobinGuillard** [lkorczowski/Tinnitus-n-Sleep#51]
It could be cool to report the mean ratio of power between events and (adaptive) baseline values:
in fact, one hypothesis to test is "are MEMA activity for tinnitus patients more powerful than for controls". When I inspect data of "pure" middle ear events, I think it's possible this hypothesis is true.

**Comment by lkorczowski** [comment]
something like :
```
amplitude = rms(epoch)
num = amplitude[labels]
denum = amplitude[np.invert(labels)]
power_ratio = np.mean(num ** 2) / np.mean(denum ** 2) 
```

**Comment by lkorczowski** [comment]
option 2
```
amplitude = rms(epoch)
power_num = np.mean(amplitude[labels]**2)
power_denum = np.mean(amplitude**2)
power_ratio = power_num / power_denum 
```

**Comment by RobinGuillard** [comment]
Better option 1
